### ISSUE TITLE
Blockstates Support

### ISSUE THREAD

**Issue by JannisX11** [HypixelDev/ResourcePackConverter#1]
The converter currently doesn't handle blockstate files. A lot of blockstates have been split up and turned into their own block ID. But even apart from that, there are two simple changes that would help a lot.

- The paths to models now start in the models folder by default. > Prepend "block/" to all model paths.
- The key for the default model inside “variants” is now an empty string “” instead of “normal”. > Rename all objects inside "variants" with the key "normal" to "".

Unfortunately, I don't know Java so I can't do a PR. Maybe someone else could.

**Comment by Plancke** [comment]
Added support for this with the directions you gave. Thank you!
