### ISSUE TITLE
hopper

### ISSUE THREAD

**Issue by angrynerd** [HypixelDev/ResourcePackConverter#11]
the model hopper_down in 1.12.2 inst renamed to hopper when converting.

**Comment by Plancke** [comment]
This is one of those issues where there are multiple values for a hopper, and I don't know all the possibilities/a good way of merging them. Ideally, the pack creator should run this and see what isn't easily converted and handle those manually.

**Comment by angrynerd** [comment]
The file its self was handled perfect its just the file wasnt renamed from
"hopper down" to "hopper".
