### ISSUE TITLE
Animated textures

### ISSUE THREAD

**Issue by angrynerd** [HypixelDev/ResourcePackConverter#2]
1.13 breaks the way certain animated textures work. this program did not fix the animated textures in the pack that i was updating. now im not sure what the changes that were made to animated textures are but the texture went from being a shine moving across the ore to this:
![2018-07-20_13 44 49](https://user-images.githubusercontent.com/24483958/43017341-b958f220-8c23-11e8-90f8-1dd4eb7a9d06.png)

**Comment by Plancke** [comment]
Please provide a resource pack download so I can check it out.

**Comment by angrynerd** [comment]
The pack is chalu's 1.11 ocd pack. I personally removed the map icons when
1.12 hit because it was the only thing that broke.
https://www.youtube.com/redirect?event=video_description&q=http%3A%2F%2Fwww.mediafire.com%2Ffile%2F0n8mwfcnuue1u38%2FOCD_Pack_1.11.zip&redir_token=Ehy9FUljt0iu5B8q-9mnotVC9eV8MTUzMjE5NjA1N0AxNTMyMTA5NjU3&v=z051rPOkweI

**Comment by Plancke** [comment]
Fixed with latest release 1.0.1

**Comment by Plancke** [comment]
Also just pushed a fix that will convert map icons to 1.13

**Comment by angrynerd** [comment]
thank you for fixing this so quickly i really appreciate this.
