### ISSUE TITLE
help with usage please?

### ISSUE THREAD

**Issue by AngiMathochist** [HypixelDev/ResourcePackConverter#4]
I downloaded the file, put it in my resource packs folder, opened my command line prompt, and pasted in the command as in the readme file. It didn't work. I tried renaming the file to match the command, removing "master" from the filename. That didn't work. Can you please tell me how to make this work? Sorry, I am a bit clueless about this. I just have a couple very small resource packs I want to convert and hoped this would make the task quick and painless.

**Comment by Plancke** [comment]
Please use the jar file provided on this page, the top file should always be latest. https://github.com/HypixelDev/ResourcePackConverter/releases/

Then it should work, please let me know.

**Comment by Plancke** [comment]
Closing as it seems resolved

**Comment by AngiMathochist** [comment]
​I haven't had time to look at this again, but I will let you know if I
have any more questions. Thanks much!​



  -- Angi
