### ISSUE TITLE
Not converting any files?

### ISSUE THREAD

**Issue by Legobuilder0813** [HypixelDev/ResourcePackConverter#5]
Running this converter doesn't convert any model/texture files in my resource pack. I think it's because of these double slashes? I'm running on Mac which uses forward slashes and it looks like the backslashes were meant for Windows. Perhaps use File.separator instead? https://github.com/HypixelDev/ResourcePackConverter/blob/7057a784032b78b9e0046cf75d3ea2ae29672511/src/main/java/net/hypixel/resourcepack/impl/NameConverter.java#L23

**Comment by Plancke** [comment]
Pushed changes to convert them to file separator, https://github.com/HypixelDev/ResourcePackConverter/releases/latest
